"""add kpr version

Revision ID: d518d8678c10
Revises: 01c28e2765da
Create Date: 2025-01-31 12:25:07.388486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d518d8678c10"
down_revision: Union[str, None] = "01c28e2765da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kriptos", sa.Column("version", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kriptos", "version")
    # ### end Alembic commands ###
