"""add hotels model

Revision ID: ff81cd3b0de6
Revises: 04169b1e12f1
Create Date: 2025-04-09 15:37:50.225802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff81cd3b0de6"
down_revision: Union[str, None] = "04169b1e12f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=False),
        sa.Column("com_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    op.create_table(
        "ecp",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employees_id", sa.Integer(), nullable=False),
        sa.Column("type_ecp", sa.String(), nullable=False),
        sa.Column("status_ecp", sa.String(), nullable=False),
        sa.Column("install_location", sa.String(), nullable=False),
        sa.Column("storage_location", sa.String(), nullable=False),
        sa.Column("sbis", sa.String(), nullable=False),
        sa.Column("chz", sa.String(), nullable=False),
        sa.Column("diadok", sa.String(), nullable=False),
        sa.Column("fns", sa.String(), nullable=False),
        sa.Column("report", sa.String(), nullable=False),
        sa.Column("fed_resours", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("finish_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employees_id"], ["employees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kriptos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employees_id", sa.Integer(), nullable=False),
        sa.Column("install_location", sa.String(), nullable=False),
        sa.Column("licens_type", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("finish_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employees_id"], ["employees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mchd",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employees_id", sa.Integer(), nullable=False),
        sa.Column("organiazation_dov_num", sa.Integer(), nullable=False),
        sa.Column("fns_dov_num", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("finish_date", sa.Date(), nullable=False),
        sa.Column("file_mchd", sa.LargeBinary(), nullable=False),
        sa.Column("file_csp", sa.LargeBinary(), nullable=True),
        sa.Column("name_of_powers", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employees_id"], ["employees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mchd")
    op.drop_table("kriptos")
    op.drop_table("ecp")
    op.drop_table("employees")
    # ### end Alembic commands ###
