name: Build Windows EXE

on: [push]  # Запускать при каждом push в репозиторий

jobs:
  build:
    runs-on: windows-latest  # Используем Windows-сервер GitHub

    steps:
      # 1. Копируем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Устанавливаем PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 4. Собираем EXE-файл
      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile --add-data "database_sqlite3.db;." main.py

      # 5. Загружаем собранный EXE в артефакты
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Program.exe
          path: dist/main.exe
